global:
  resolve_timeout: 5m

route:
  receiver: "self-healing-webhook"

receivers:
  - name: "self-healing-webhook"
    webhook_configs:
      - url: "http://localhost:5001/webhook"
        send_resolved: true